version: '3.1'

services:
  mysql:
    container_name: mysql
    image: 'mysql:8'
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 4D#BF_RPtrQ3Q2n=VuNR!k5WvhLsmB#8
      MYSQL_DATABASE: omm
      MYSQL_USER: omm
      MYSQL_PASSWORD: LhWxqJ^?pn@6AK+md6wZ_hsA=Qz52DSm

  server:
    container_name: openmonkeymind
    image: cogsci/omm-server:latest
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      BASE_URL:
      API_URL:
      PORT:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: omm
      DB_PASSWORD: LhWxqJ^?pn@6AK+md6wZ_hsA=Qz52DSm
      DB_DATABASE: omm
      APP_KEY: 2wsjLSopTjD6WQEztTYIZgCFou8wpLJn
      MAIL_CONNECTION:
      SMTP_HOST:
      SMTP_PORT:
      MAIL_USERNAME:
      MAIL_PASSWORD:
      MAIL_SENDER_NAME:
      MAIL_SENDER_EMAIL:
    depends_on:
      - mysql
    restart: on-failure
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - files-data:/img/public/files

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025 # smtp server
      - 3001:8025 # web ui

volumes:
  mysql-data:
  files-data:
