version: '3.1'

services:
  mysql:
    container_name: mysql
    image: 'mysql:8'
    restart: always
    # volumes:
    #   - /var/data/mysql:/var/lib/mysql
    #   - /etc/mysql:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 4D#BF_RPtrQ3Q2n=VuNR!k5WvhLsmB#8
      MYSQL_DATABASE: omm
      MYSQL_USER: omm
      MYSQL_PASSWORD: LhWxqJ^?pn@6AK+md6wZ_hsA=Qz52DSm

  server:
    # image: docker.pkg.github.com/open-cogsci/omm-server/omm-server:0.1.12
    build: .
    environment:
      HOST: 0.0.0.0
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: omm
      DB_PASSWORD: LhWxqJ^?pn@6AK+md6wZ_hsA=Qz52DSm
      DB_DATABASE: omm
    depends_on:
      - mysql
    restart: on-failure
    ports:
      - 3000:3000