version: '3.1'

services:
  mysql:
    container_name: mysql
    image: 'mysql:8'
    restart: always
    ports:
      - "3306:3306"
    # volumes:
    #   - /var/data/mysql:/var/lib/mysql
    #   - /etc/mysql:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: omm
      MYSQL_USER: omm
      MYSQL_PASSWORD: 4tt3nt10n!

  server:
    image: registry.github.com/open-cogsci/omm-server:latest
    environment:
      DB_PORT: 3306
      DB_USER: omm
      DB_PASSWORD: 4tt3nt10n!
      DB_HOST: mysql
      DB_DATABASE: omm
    depends_on:
      - mysql
    ports:
      - 80:80