version: '3.1'

services:
  mysql:
    container_name: mysql
    image: 'mysql:8'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /var/data/mysql:/var/lib/mysql
      - /etc/mysql:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: cdr
      MYSQL_PASSWORD: secret123

  server:
    image: registry.github.com/open-cogsci/omm-server
    environment:
      PORT: 3306
      POSTGRES_PORT: 5432
      POSTGRES_USER: omm
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_HOST: mysql
      POSTGRES_DB: omm
    depends_on:
      - mysql
    ports:
      - 3000:80